library(checkpoint)
library(plyr)
library(tidyverse)
library(lmerTest)
library(lme4)
library(emmeans) 
library(multcomp) 
library(multcompView) 
library(pscl)
library(arm)
library(MuMIn)
library(optimx)
library(xtable)

